import "./globals.css";

export const metadata = {
  title: "Ristorante Pizzeria Al Teatro - Desenzano del Garda (BS)",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="it">
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
